### ISSUE TITLE
"Usage Instructions" link in README leads to 404

### ISSUE THREAD

**Issue by arisinwonderland** [leotorrez/ZZ-Model-Importer#4]
When clicking the link to the "Usage Instructions" page in the eponymous section of the README, it links to the file [/Guides/UsageInstructions.md](https://github.com/leotorrez/ZZ-Model-Importer/blob/main/Guides/UsageInstructions.md), which is a nonexistent file in the current version of the repo.

**Comment by leotorrez** [comment]
Hasn't been added yet. This is a known issue. Feel free to find My profile in gamebanana for updated tutorials
